export const PostIcon = [
  {
    url: "./static/Video.png",
    position: "0 -308px",
    bg: true,
    title: "Ảnh/Video",
    width: "w-13",
    translate: "-translate-y-20 -translate-x-2",
    id: 1,
  },
  {
    url: "./static/Tag.png",
    position: "0 -283px",
    bg: true,
    title: "Gắn Thẻ Người Khác",
    width: "w-36",
    translate: "-translate-y-20 -translate-x-12",
    id: 2,
  },
  {
    url: "./static/Emotion.png",
    position: "0 -258px",
    bg: true,
    title: "Cảm Xúc/Hoạt động",
    width: "w-36",
    translate: "-translate-y-20 -translate-x-12",
    id: 3,
  },
  {
    url: "./static/CheckIn.png",
    position: "0 -225px",
    bg: true,
    title: "Check-in",
    width: "w-20",
    translate: "-translate-y-20 -translate-x-4",
    id: 4,
  },
  {
    url: "./static/Activity.png",
    position: "0 -100px",
    bg: true,
    title: "Tổ Chức buổi H&Đ",
    width: "w-36",
    translate: "-translate-y-20 -translate-x-12",
    id: 5,
  },
  {
    url: "./static/More.png",
    position: "0 -183px",
    bg: true,
    title: "Xem Thêm",
    width: "w-20",
    translate: "-translate-y-20 -translate-x-4",
    id: 6,
  },
];
