export const Emoji = [
  {
    type: "like",
    id: 1,
    content: "Thích",
    color: "-primary",
    font: "medium",
  },
  {
    type: "love",
    id: 2,
    content: "Yêu thích",
    color: "-love",
    font: "medium",
  },
  {
    type: "care",
    id: 3,
    content: "Thương Thương",
    color: "-yellow-300",
    font: "medium",
  },
  {
    type: "haha",
    id: 4,
    content: "haha",
    color: "-yellow-300",
    font: "medium",
  },
  {
    type: "wow",
    id: 5,
    content: "wow",
    color: "-yellow-300",
    font: "medium",
  },
  {
    type: "sad",
    id: 6,
    content: "Buồn",
    color: "-yellow-300",
    font: "medium",
  },
  {
    type: "angry",
    id: 7,
    content: "Giận dữ",
    color: "-angry",
    font: "medium",
  },
  {
    type: "unLike",
    id: 8,
    content: "Thích",
    color: "",
    font: "medium",
  },
];
