import Head from "next/head";
import { Navbar } from "../component/Navbar/Menu";
import { Hero } from "../component/Hero/Hero";
const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
    </div>
  );
};

export default Home;
